# Generated by Django 5.1.4 on 2024-12-20 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_backend', '0008_product_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount_percentage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
